### ISSUE TITLE
Criar página de calendário

### ISSUE THREAD

**Issue by quaresmateo** [SEDEPTI-BC/sad-front-end#18]
Nesta página, o usuário poderá gerenciar os horários disponíveis para os agendamentos dos eventos, como podemos ver no mockup abaixo:

![image](https://user-images.githubusercontent.com/26655732/79008060-f2c80f00-7b32-11ea-8153-c0382014b9fa.png)

Quando o usuário escollher a opção de desativar dia, será mostrado um pop-up com os campos:
- Título
- Descrição
- Dia e hora de início
- Dia e hora do fim

Este mockup mostrar como deve ser, mais ou menos, este pop-up:

![mockup calendario sad-bc](https://user-images.githubusercontent.com/26655732/79008557-058f1380-7b34-11ea-81f3-8a24aa20c1d0.png)

A paginação dos dias desativados devem ser por loading.

To do
-----

- [x] exibir dias desativados e eventos
- [x] excluir dia desativado
- [x] marca dia em há evento/dia desativado do calendário
- [x] dia inteiro desabilitado não precisa exibir horário
- [x] desativar dia
- [ ] editar dia desativado

**Comment by sedepti** [comment]
Falta o componente para desativar dias

**Comment by quaresmateo** [comment]
- [ ] Dropdown de sesativar dias

- [ ] apagar dia que foi desativado (popup de confirmação)
